package com.lotusir.courseserver.utils;

public enum CourseEnum {
    SELECT_SUCCESS,
    SELECT_FAIL_FULL,
    SELECT_FAIL_HAS,
    SELECT_FAIL_COURSE_NOT_EXIST,
    DROP_SUCCESS,
    DROP_FAIL_COURSE_NOT_HAS,
    DROP_FAIL_COURSE_NOT_EXIST,
    DELETE_SUCCESS,
    DELETE_FAIL_INVALID_ID,
    DELETE_FAIL_REFERENCE_ERR,
    CREATE_FAIL_ID_EXIST,
    CREATE_SUCCESS;

}
